Repository ygor-sena/42cursus-ft-irc, pull requests merged in 2024-05, with the labels that each got.

#2 feat: added irc authetication
  Client.cpp
  Client.hpp
  Makefile
  Replies.hpp
  Server.cpp
  Server.hpp
  estudos.txt
  main.cpp
Labels: enhancement, fix

#3 feat: add GitHub Action and Criterion workflow
  .github/workflows/ft_irc_actions.yml
  Makefile
  include/Client.hpp
  include/Replies.hpp
  include/Server.hpp
  src/Client.cpp
  src/Server.cpp
  src/main.cpp
  tests/Makefile
  tests/TestServer.cpp
  tests/Utils.cpp
  tests/Utils.hpp
Labels: enhancement

#4 refactor: adding a new structure for executing commands
  Makefile
  include/Client.hpp
  include/Replies.hpp
  include/Server.hpp
  src/Client.cpp
  src/Server.cpp
Labels: enhancement

#16 feat: added missing server structure
  Makefile
  include/Channel.hpp
  include/Client.hpp
  include/Replies.hpp
  include/Server.hpp
  src/Channel.cpp
  src/Server.cpp
  src/commands/Invite.cpp
  src/commands/Join.cpp
  src/commands/Kick.cpp
  src/commands/Mode.cpp
  src/commands/Nick.cpp
  src/commands/Part.cpp
  src/commands/Pass.cpp
  src/commands/Privmsg.cpp
  src/commands/Quit.cpp
  src/commands/Topic.cpp
  src/commands/User.cpp
Labels: enhancement

#20 feat(part): add PART command and its unit tests
  include/Channel.hpp
  include/Client.hpp
  include/Replies.hpp
  include/Server.hpp
  src/Channel.cpp
  src/Server.cpp
  src/commands/Kick.cpp
  src/commands/Part.cpp
  tests/Makefile
  tests/TestInvite.cpp
  tests/TestKick.cpp
  tests/TestPart.cpp
  tests/TestTopic.cpp
Labels: enhancement

#21 feat: add PRIVMSG for clients and remove _is_registered
  include/Channel.hpp
  include/Client.hpp
  include/Replies.hpp
  include/Server.hpp
  src/Channel.cpp
  src/Client.cpp
  src/Server.cpp
  src/commands/Invite.cpp
  src/commands/Join.cpp
  src/commands/Kick.cpp
  src/commands/Nick.cpp
  src/commands/Part.cpp
  src/commands/Pass.cpp
  src/commands/Privmsg.cpp
  src/commands/User.cpp
  tests/Makefile
  tests/TestInvite.cpp
  tests/TestKick.cpp
  tests/TestNick.cpp
  tests/TestPart.cpp
  tests/TestPrivmsg.cpp
  tests/TestUser.cpp
Labels: enhancement, fix

#23 fix: adjusted commands
  include/Channel.hpp
  include/Client.hpp
  include/Replies.hpp
  include/Server.hpp
  ircserv
  src/Channel.cpp
  src/Client.cpp
  src/Server.cpp
  src/commands/Invite.cpp
  src/commands/Join.cpp
  src/commands/Kick.cpp
  src/commands/Mode.cpp
  src/commands/Nick.cpp
  src/commands/Part.cpp
  src/commands/Pass.cpp
  src/commands/Privmsg.cpp
  src/commands/Quit.cpp
  src/commands/Topic.cpp
  src/commands/User.cpp
  src/main.cpp
Labels: enhancement

#24 fix(privmsg): broadcast msgs to channel is now working
  include/Channel.hpp
  include/Client.hpp
  ircserv
  src/Channel.cpp
  src/Client.cpp
  src/commands/Invite.cpp
  src/commands/Privmsg.cpp
  tests/TestInvite.cpp
Labels: fix

#25 fix: adjusted mode and nick command
  include/Channel.hpp
  include/Server.hpp
  ircserv
  src/Channel.cpp
  src/Server.cpp
  src/commands/Invite.cpp
  src/commands/Join.cpp
  src/commands/Kick.cpp
  src/commands/Mode.cpp
  src/commands/Quit.cpp
  src/commands/Topic.cpp
  tests/TestJoin.cpp
  tests/invite
Labels: fix

#27 feat: refactor bot and add !quote to marvin commands
  Makefile
  include/Bot.hpp
  include/Channel.hpp
  include/Client.hpp
  include/MarvinBot.hpp
  include/Replies.hpp
  include/Server.hpp
  src/Bot.cpp
  src/Channel.cpp
  src/Client.cpp
  src/MarvinBot.cpp
  src/Server.cpp
  src/commands/Invite.cpp
  src/commands/Kick.cpp
  src/commands/Quit.cpp
  tests/Makefile
  tests/TestInvite.cpp
  tests/TestMarvinBot.cpp
  tests/TestQuit.cpp
Labels: enhancement, fix, bonus

#28 fix: fix valgrind case of memory leak when last channel client uses QUIT cmd
  src/commands/Quit.cpp
Labels: fix

#29 feat: add unit tests for TOPIC command
  include/Channel.hpp
  src/Channel.cpp
  src/commands/Topic.cpp
  tests/TestKick.cpp
  tests/TestMarvinBot.cpp
  tests/TestTopic.cpp
  tests/TestUser.cpp
Labels: enhancement, fix

#30 feat: add more unit tests to Nick command
  ircserv
  src/Server.cpp
  src/commands/Invite.cpp
  src/commands/Join.cpp
  src/commands/Nick.cpp
  src/commands/Pass.cpp
  src/commands/User.cpp
  tests/TestNick.cpp
Labels: enhancement

#31 feat: add more unit test for User command
  src/commands/Kick.cpp
  src/commands/Mode.cpp
  src/commands/Part.cpp
  src/commands/User.cpp
  tests/Makefile
  tests/TestMode.cpp
  tests/TestNick.cpp
  tests/TestUser.cpp
Labels: enhancement

#33 feat: add tests for pass command
  ircserv
  tests/Makefile
  tests/TestNick.cpp
  tests/TestPass.cpp
  tests/TestUser.cpp
Labels: enhancement

#35 fix(JOIN): fix uninitialized variable bug and add code automation with .clang-format
  .clang-format
  include/Channel.hpp
  include/Client.hpp
  include/MarvinBot.hpp
  include/Replies.hpp
  include/Server.hpp
  src/Channel.cpp
  src/Client.cpp
  src/MarvinBot.cpp
  src/Server.cpp
  src/commands/Invite.cpp
  src/commands/Join.cpp
  src/commands/Kick.cpp
  src/commands/Mode.cpp
  src/commands/Nick.cpp
  src/commands/Part.cpp
  src/commands/Pass.cpp
  src/commands/Privmsg.cpp
  src/commands/Quit.cpp
  src/commands/Topic.cpp
  src/commands/User.cpp
  src/main.cpp
  tests/TestInvite.cpp
  tests/TestJoin.cpp
  tests/TestKick.cpp
  tests/TestMarvinBot.cpp
  tests/TestMode.cpp
  tests/TestNick.cpp
  tests/TestPart.cpp
  tests/TestPass.cpp
  tests/TestPrivmsg.cpp
  tests/TestQuit.cpp
  tests/TestSplitMessage.cpp
  tests/TestTopic.cpp
  tests/TestUser.cpp
  tests/Utils.cpp
  tests/Utils.hpp
Labels: documentation, fix

#36 fix!: ircserv does not raise Valgrind flags anymore
  include/Channel.hpp
  include/Client.hpp
  include/Server.hpp
  src/Channel.cpp
  src/Client.cpp
  src/MarvinBot.cpp
  src/Server.cpp
  src/commands/Privmsg.cpp
  src/commands/Quit.cpp
  tests/TestInvite.cpp
  tests/TestKick.cpp
  tests/TestMarvinBot.cpp
  tests/TestNick.cpp
  tests/TestPart.cpp
  tests/TestPass.cpp
  tests/TestPrivmsg.cpp
  tests/TestQuit.cpp
  tests/TestTopic.cpp
  tests/TestUser.cpp
Labels: fix

#37 fix: remove segfault in mode command
  src/commands/Mode.cpp
Labels: enhancement

#38 feat: add unit tests for Mode command
  include/Server.hpp
  src/commands/Mode.cpp
  tests/TestMode.cpp
Labels: enhancement
