Repository ygor-sena/42cursus-ft-irc, pull requests merged in 2024-06, with the labels that each got.

#39 fix!: add required format response by Hexchat IRC client
  include/Replies.hpp
  include/Server.hpp
  src/Channel.cpp
  src/Client.cpp
  src/Server.cpp
  src/commands/Join.cpp
  src/commands/Mode.cpp
  src/commands/Nick.cpp
  src/commands/Privmsg.cpp
  src/commands/User.cpp
Labels: enhancement, fix

#41 refactor: better unit tests files formatting
  include/Channel.hpp
  include/Client.hpp
  include/Replies.hpp
  include/Server.hpp
  ircserv
  src/Channel.cpp
  src/Client.cpp
  src/Server.cpp
  src/commands/Invite.cpp
  src/commands/Join.cpp
  src/commands/Kick.cpp
  src/commands/Mode.cpp
  src/commands/Nick.cpp
  src/commands/Part.cpp
  src/commands/Pass.cpp
  src/commands/Privmsg.cpp
  src/commands/Topic.cpp
  src/commands/User.cpp
  tests/TestMode.cpp
  tests/TestNick.cpp
  tests/TestPart.cpp
  tests/TestPass.cpp
  tests/TestTopic.cpp
  tests/TestUser.cpp
Labels: enhancement, fix

#42 feat: refactor invite and mode command
  include/Channel.hpp
  include/Server.hpp
  ircserv
  src/Server.cpp
  src/commands/Invite.cpp
  src/commands/Join.cpp
  src/commands/Kick.cpp
  src/commands/Mode.cpp
  src/commands/Privmsg.cpp
Labels: enhancement

#43 feat: added unit tests for join command and refactoring
  include/Replies.hpp
  ircserv
  src/commands/Join.cpp
  tests/TestJoin.cpp
Labels: enhancement

#44 cleanup: removing comments from code
  include/Server.hpp
  src/MarvinBot.cpp
  src/commands/Join.cpp
  src/commands/Mode.cpp
  src/commands/Nick.cpp
  src/commands/Privmsg.cpp
  src/commands/Quit.cpp
  tests/TestInvite.cpp
  tests/TestKick.cpp
  tests/TestPass.cpp
Labels: enhancement

#45 feat(main): add user and pwd to be passed as user args
  include/Replies.hpp
  include/Server.hpp
  src/Server.cpp
  src/main.cpp
  tests/TestKick.cpp
Labels: enhancement, fix

#47 fix(marvinbot)!: fix marvinbot cmds not working on Hexchat IRC client
  include/MarvinBot.hpp
  include/Replies.hpp
  include/Server.hpp
  src/MarvinBot.cpp
  src/Server.cpp
  src/commands/Privmsg.cpp
Labels: fix

#49 docs: add Doxygen comments to enhance code documentation
  include/Channel.hpp
  include/Client.hpp
  include/MarvinBot.hpp
  include/Replies.hpp
  include/Server.hpp
  src/MarvinBot.cpp
  src/Server.cpp
  src/commands/Privmsg.cpp
  tests/TestInvite.cpp
  tests/TestJoin.cpp
  tests/TestKick.cpp
  tests/TestMarvinBot.cpp
  tests/TestMode.cpp
  tests/TestNick.cpp
  tests/TestPart.cpp
  tests/TestPass.cpp
  tests/TestPrivmsg.cpp
  tests/TestQuit.cpp
  tests/TestSplitMessage.cpp
  tests/TestTopic.cpp
  tests/TestUser.cpp
  tests/Utils.cpp
  tests/Utils.hpp
Labels: documentation

#50 "fix!: ircserv now handles Ctrl-D correctly"
  include/Client.hpp
  include/Replies.hpp
  include/Server.hpp
  src/Client.cpp
  src/MarvinBot.cpp
  src/Server.cpp
  src/commands/Mode.cpp
Labels: fix

#51 fix: add again the files corrections of MarvinBot working on Hexchat
  include/Replies.hpp
  src/MarvinBot.cpp
Labels: fix

#52 fix: fix marvinbot whois command
  src/MarvinBot.cpp
Labels: fix
